version: '3.8'

services:
  dns-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"    # Maps the web app port to the host
      - "53:53/udp"    # Maps the DNS server's UDP port to the host
      - "53:53/tcp"    # Maps the DNS server's TCP port to the host
    environment:
      NODE_ENV: production
    restart: always